version: "3"

services:
    backend:
        build:
            context: ./django
        command: sh -c "python manage.py migrate &&
            gunicorn backend.wsgi --bind 0.0.0.0:8000"
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=devdb
            - DB_USER=devuser
            - DB_PASS=changeme
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        volumes:
            - dev-db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=changeme
            - POSTGRES_DB=devdb

    frontend:
        command: npm start
        build:
            context: ./react/frontend
        volumes:
            - react_build:/react/build
        depends_on:
            - backend
        ports:
            - "3000:3000"

volumes:
    react_build:
    dev-db-data:
